CMSP-628 WPMS Updates
pantheon-systems/updatinate pull request #118
Opened 2024-01-11 21:06 UTC by rwagner00

### Overview
This pull request:

Resolves https://getpantheon.atlassian.net/browse/CMSP-628 

| Q             | A
| ------------- | ---
| Bug fix?      | yes-ish
| New feature?  | no
| Has tests?    | yes
| BC breaks?    | no     
| Deprecations? | no 

### Summary
Causes normal commits without tags to also trigger the update process.

2024-01-11 21:14 UTC, jazzsequence reviewed
do we have tests for the WPMS repository? like a fixture in pantheon-fixtures for that? If not, we should make one and ensure that the thing actually does what it says on the box.

2024-01-11 21:45 UTC, pwtyler commented
+1 on WPMS fixture tests.

2024-01-12 16:03 UTC, pwtyler requested changes
I didn't really get into it line by line to give any more specific of a suggestion, but reading through `projectUpstreamUpdate`, I have the sense the old code checking the version numbers is made redundant by the fact that we're now just checking commits. That could likely just be dropped since the tags are made redundant by that `||`. If the tags give us reason to update, so will the commit comparison.

2024-01-23 17:35 UTC, pwtyler requested changes
Copying over review from https://github.com/pantheon-systems/update-tool/pull/119/

2024-01-23 17:35 UTC, pwtyler commented on tests/ProjectCommandsTest.php
> +        // Try to create an upstream update PR for our wpms fixture
Drop commented code.

2024-01-23 17:35 UTC, pwtyler commented on tests/src/Fixtures.php
> +
only instance of this is in commented code. remove.

2024-01-23 17:35 UTC, pwtyler commented on src/Update/Methods/WpCliUpdate.php
> +        $forceDbDrop = (!empty($parameters['force-db-drop']) || $this->forceDbDrop) ?? false;
This doesn't need to be a clever one liner. make more verbose.

2024-01-23 19:10 UTC, jazzsequence commented
@pwtyler I'm seeing a lot of stuff that would still use the version checking stuff -- if for no other reason than for update notifications that _are_ triggered by tags. If we removed all of it, I think we would break a lot of things. The change @rwagner00 made in https://github.com/pantheon-systems/update-tool/pull/118/commits/3679b2d763e3c9820dbd11be4a118274649c36a0 are probably sufficient so we aren't _requiring_ that to trigger updates.

2026-04-20 22:21 UTC, closed without merging